# Auto-generated by Buildozer
[app]

# App identity
title = Road Rush
package.name = roadrush
package.domain = org.roadrush

# Source
source.dir = .
source.include_exts = py,png,jpg,jpeg,gif,bmp,wav,ogg,mp3

# Version
version = 1.0

# Requirements — pygame bootstrap runs on SDL2
requirements = python3,pygame

# Orientation (portrait for a vertical endless runner)
orientation = portrait

# Android
android.permissions = VIBRATE
android.archs = arm64-v8a, armeabi-v7a
android.bootstrap = sdl2
android.minapi = 21
android.sdk = 34
android.ndk = 25b

# Fullscreen
fullscreen = 1

# iOS (ignored for Android build)
[buildozer]
log_level = 2
warn_on_root = 1
